(add-to-list 'load-path "~/.emacs.d/package/elisp-tree-sitter/core")
(add-to-list 'load-path "~/.emacs.d/package/elisp-tree-sitter/lisp")
(add-to-list 'load-path "~/.emacs.d/package/tree-sitter-langs")

(require 'tree-sitter)
(require 'tree-sitter-hl)
(require 'tree-sitter-langs)
(require 'tree-sitter-debug)
(require 'tree-sitter-query)

;; Disable italic for tree-sitter property face (affects YAML keys, JSON keys, CSS properties, etc.)
(set-face-attribute 'tree-sitter-hl-face:property nil :slant 'normal)

(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
;; Only register modes that do NOT have a built-in `*-ts-mode' replacement
;; in this config. Languages already routed to treesit (bash, css, go, java,
;; javascript/typescript/tsx, json, python, ruby, sh, yaml, dockerfile) are
;; intentionally omitted -- their buffers use `*-ts-mode' which is driven by
;; the built-in `treesit' API, not by elisp-tree-sitter.
(setq tree-sitter-major-mode-language-alist '((actionscript-mode . actionscript)
                                              (ada-mode . ada)
                                              (agda-mode . agda)
                                              (agda2-mode . agda)
                                              (arduino-mode . arduino)
                                              (astro-mode . astro)
                                              (fish-mode . fish)
                                              (asm-mode . asm)
                                              (fasm-mode . asm)
                                              (masm-mode . asm)
                                              (nasm-mode . asm)
                                              (gas-mode . asm)
                                              (beancount-mode . beancount)
                                              (bibtex-mode . bibtex)
                                              (c-mode . c)
                                              (caml-mode . ocaml)
                                              (clojure-mode . clojure)
                                              (lisp-mode . commonlisp)
                                              (lisp-interaction-mode . commonlisp)
                                              (csharp-mode . c-sharp)
                                              (c++-mode . cpp)
                                              (cmake-mode . cmake)
                                              (d-mode . d)
                                              (dart-mode . dart)
                                              (csv-mode . csv)
                                              (elm-mode . elm)
                                              (elixir-mode . elixir)
                                              (emacs-lisp-mode . elisp)
                                              (erlang-mode . erlang)
                                              (ess-r-mode . r)
                                              (fennel-mode . fennel)
                                              (f90-mode . fortran)
                                              (fortran-mode . fortran)
                                              (gdscript-mode . gdscript)
                                              (git-commit-mode . gitcommit)
                                              (git-rebase-mode . git-rebase)
                                              (gitattributes-mode . gitattributes)
                                              (gitignore-mode . gitignore)
                                              (gleam-mode . gleam)
                                              (glsl-mode . glsl)
                                              (groovy-mode . groovy)
                                              (jenkinsfile-mode . groovy)
                                              (haskell-mode . haskell)
                                              (haxe-mode . haxe)
                                              (hcl-mode . hcl)
                                              (terraform-mode . hcl)
                                              (heex-mode . heex)
                                              (hlsl-mode . hlsl)
                                              (html-mode . html)
                                              (gfm-mode . markdown)
                                              (mhtml-mode . html)
                                              (nix-mode . nix)
                                              (jai-mode . jai)
                                              (jsonnet-mode . jsonnet)
                                              (julia-mode . julia)
                                              (kotlin-mode . kotlin)
                                              (latex-mode . latex)
                                              (llvm-mode . llvm)
                                              (llvm-mir-mode . llvm-mir)
                                              (lua-mode . lua)
                                              (magik-mode . magik)
                                              (makefile-mode . make)
                                              (makefile-automake-mode . make)
                                              (makefile-gmake-mode . make)
                                              (makefile-makepp-mode . make)
                                              (makefile-bsdmake-mode . make)
                                              (makefile-imake-mode . make)
                                              (matlab-mode . matlab)
                                              (mermaid-mode . mermaid)
                                              (meson-mode . meson)
                                              (ninja-mode . ninja)
                                              (noir-mode . noir)
                                              (ocaml-mode . ocaml)
                                              (org-mode . org)
                                              (pascal-mode . pascal)
                                              (perl-mode . perl)
                                              (php-mode . php)
                                              (qss-mode . css)
                                              (prisma-mode . prisma)
                                              (pygn-mode . pgn)
                                              (racket-mode . racket)
                                              (rst-mode . rst)
                                              (rust-mode . rust)
                                              (rustic-mode . rust)
                                              (scala-mode . scala)
                                              (scheme-mode . scheme)
                                              (solidity-mode . solidity)
                                              (smithy-mode . smithy)
                                              (sql-mode . sql)
                                              (svelte-mode . svelte)
                                              (swift-mode . swift)
                                              (tablegen-mode . tablegen)
                                              (toml-mode . toml)
                                              (conf-toml-mode . toml)
                                              (tcl-mode . tcl)
                                              (tuareg-mode . ocaml)
                                              (twig-mode . twig)
                                              (typst-mode . typst)
                                              (verilog-mode . verilog)
                                              (vhdl-mode . vhdl)
                                              (nxml-mode . xml)
                                              (k8s-mode . yaml)
                                              (zig-mode . zig)))

(provide 'init-tree-sitter)
